name: maxmi
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.9.3
  - aiosignal=1.2.0
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - future=0.18.3
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.22.0
  - grpc-cpp=1.48.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - multidict=6.0.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=1.1.1w
  - pillow=9.4.0
  - pip=23.2.1
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.29.0
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.21.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.2.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - cachetools==5.3.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==3.0.0
      - decorator==4.4.2
      - diffusers==0.10.2
      - dm-control==0.0.403778684
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - executing==1.2.0
      - fasteners==0.18
      - fonttools==4.39.4
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.9
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.2
      - gym==0.21.0
      - h5py==3.8.0
      - huggingface-hub==0.16.4
      - imageio==2.28.1
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.8.0
      - importlib-resources==5.12.0
      - ipdb==0.13.13
      - ipython==8.12.2
      - jedi==0.19.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - llvmlite==0.40.1
      - lxml==4.9.2
      - mani-skill2==0.4.2
      - markdown==3.4.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - moviepy==1.0.3
      - mujoco-py==2.1.2.14
      - numba==0.57.1
      - numpy==1.23.1
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pandas==2.0.1
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - proglog==0.1.10
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyopengl==3.1.6
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - rtree==1.0.1
      - safetensors==0.3.1
      - sapien==2.2.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.22.2
      - setproctitle==1.3.2
      - smmap==5.0.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - tabulate==0.9.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - timm==0.9.5
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.31.0
      - transforms3d==0.4.1
      - trimesh==3.21.6
      - tzdata==2023.3
      - wandb==0.15.2
      - wcwidth==0.2.6
      - werkzeug==2.3.6
      - zipp==3.15.0